FROM node:18
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY src/ ./src/
COPY index.html /app/
COPY vite.config.ts /app/
RUN npm run build:frontend
EXPOSE 3000
CMD ["npm", "run", "preview", "--", "--host"]